services:
  api:
    build: ./
    environment:
      - "SPRING_PROFILES_ACTIVE=prod"
      - "spring.datasource.url=jdbc:mysql://mysql:3306/haeger_management"
    ports:
      - 8081:8081
    depends_on:
      - mysql
  mysql:
    image: mysql
    environment:
      - MYSQL_DATABASE=haeger_management
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
  frontend:
    image: haeger-frontend:latest
    depends_on:
      - api
    ports:
      - 8080:8080


